### ISSUE TITLE
Curiosità

### ISSUE THREAD

**Issue by whiplash78** [EMaX0/sod_cb01#1]
Ciao EMaX0,
sei per caso @@@@@@@ ?

Se non è così, scusa il disturbo...

PS Non ho trovato altro modo di contattarti, per quello ho aperto questa"issue".

**Comment by EMaX0** [comment]
Yep :D

**Comment by whiplash78** [comment]
Mi potresti contattare su Telegram?

**Comment by EMaX0** [comment]
Ti ho mandato un'email su whipl....@gmail.com
Non uso Telegram da tanto tempo
